### ISSUE TITLE
Line Running Through Active Tab

### ISSUE THREAD

**Issue by Shankarelius** [Godiesc/firefox-gx#179]
The line at the top of the theme is running through the "active" tab when it should only go around it. This is either some setting I am unaware of or a bug! Let me know what I can do! Thank you for your time and the theme!

![Screenshot (69)](https://github.com/Godiesc/firefox-gx/assets/127240329/c18223a7-791d-446b-b825-47fdba841f00)

**Comment by ItzELECTR0** [comment]
I also have this problem
![image](https://github.com/Godiesc/firefox-gx/assets/82042993/3f85cb28-96e0-4411-8f4e-bdfab1956aa3)

**Comment by Godiesc** [comment]
hi, that problem was solved with an update in the file ogx_tabs-bar, you can see the issue here: https://github.com/Godiesc/firefox-gx/issues/178

**Comment by Shankarelius** [comment]
I already replaced all the files with your latest version of Firefox GX. The issue appeared when I was trying to get the left side-bar to show up and messing with getting the configuration right.

**Comment by Godiesc** [comment]
The release '[FirefoxGX_Release_v.128](https://github.com/Godiesc/firefox-gx/releases/tag/v.9.3)'  is for Firefox 128 and works with Firefox 128, if you use beta or nightly versions you should download the theme from the button `code-> download zip`.

**Comment by ItzELECTR0** [comment]
I was confused when downloading the latest release didn't fix it, but downloading the main branch did. Thanks for the fix, you're awesome for making this theme!

**Comment by Shankarelius** [comment]
@Godiesc Ahh ok, I see what you mean! Done and fixed! Thank you for clarifying and thank you for the awesome theme! You're the man!

**Comment by leowh11** [comment]
the solution from the latest release didn't work for me :(
![image](https://github.com/user-attachments/assets/e63832d8-8be2-425b-8b17-51f62918492e)

**Comment by ashley-graves** [comment]
having this issue on Librewolf 128.0-2 using latest code download on Linux

**Comment by Godiesc** [comment]
> having this issue on Librewolf 128.0-2 using latest code download on Linux

hi, for v.128 you should download the theme from the 'Releases' section, and as you can see in other comments LibreWolf has [some issues](https://github.com/Godiesc/firefox-gx/issues/177#issuecomment-2228019397).

**Comment by ashley-graves** [comment]
> > having this issue on Librewolf 128.0-2 using latest code download on Linux
> 
> hi, for v.128 you should download the theme from the 'Releases' section, and as you can see in other comments LibreWolf has [some issues](https://github.com/Godiesc/firefox-gx/issues/177#issuecomment-2228019397).

Still the same issue using the release.
![rBt4grcwkEwZSPds](https://github.com/user-attachments/assets/93317027-5458-4ae8-9f0c-62fd0512f614)

**Comment by Godiesc** [comment]
I don't use librewolf to test the theme, but you have only 2 places to download the theme, one is from the 'Releases' section and other from the button `code` -> `download zip`, if both don't works for you maybe librewolf isn't compatible with this theme.

**Comment by ashley-graves** [comment]
turns out I was modifying the wrong profile - apologies for the confusion

**Comment by Godiesc** [comment]
solved.
